### ISSUE TITLE
Getting Error message after running BUILD2.bat with arguments that aren't the help argument

### ISSUE THREAD

**Issue by flowerbearttv** [Iambian/CEVidium#15]
The exact error is 
```powershell
Loading libraries...
External library file loading
Traceback (most recent call last):
  File "G:\CEVidium-master\CEVENCODER\tools\toolkit2.py", line 59, in <module>
    settings = extern.Config(extern.STATUSF)
  File "G:\CEVidium-master\CEVENCODER\tools\extern.py", line 407, in __init__
    self.vname,self.enco,self.titl,self.auth = self.arr
ValueError: not enough values to unpack (expected 4, got 0)
```
I converted the script to python 3 using 2to3 and this is the error I'm getting

**Comment by Iambian** [comment]
This looks like a problem with `obj/curstate` being damaged. Delete that file and try again.

Either way, these build scripts are going to become obsolete fairly soon, and I want to clean up the issues tracker. If you really want to persist and haven't given up yet over these past (... oh my...) three years, and have more problems, please create another issue.

Case closed. For now.
